// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvYD6zDVI7bxeQRvYwhIMvDdVzLlu0l8',
    appId: '1:7658457393:android:51c57e19b4a7b36c718810',
    messagingSenderId: '7658457393',
    projectId: 'bobp-9e645',
    storageBucket: 'bobp-9e645.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_nFpB5-lahnXIbBgGo0RnhRXfmh_auc',
    appId: '1:7658457393:ios:e0da12026c205cb8718810',
    messagingSenderId: '7658457393',
    projectId: 'bobp-9e645',
    storageBucket: 'bobp-9e645.firebasestorage.app',
    iosBundleId: 'org.bobp.catchDocumentationApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDlOahD3rP3e4jBktJl4nIIW6YSoSRgU',
    appId: '1:7658457393:web:6a96cb9f369c3dc9718810',
    messagingSenderId: '7658457393',
    projectId: 'bobp-9e645',
    authDomain: 'bobp-9e645.firebaseapp.com',
    storageBucket: 'bobp-9e645.firebasestorage.app',
    measurementId: 'G-KXMM5EQ522',
  );
}
